[wokwi]
version = 1
firmware = '.pio/build/esp32doit-devkit-v1/firmware.bin'
elf = '.pio/build/esp32doit-devkit-v1/firmware.elf'

# Browser at http://localhost:8180 -> port 80 of the simulated ESP32
[[net.forward]]
from = "localhost:8180"
to = "target:80"
